language: node_js
sudo: required
services:
  - docker
node_js:
  - "lts/carbon"
jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run compile
        - npm run test
    - stage: package
      script:
        - npm install
        - npm run compile
        - docker build -t tksukhu/nxplorerjs-microservice .
