language: node_js
sudo: required
services:
  - docker
node_js:
  - "lts/carbon"
  - "10"
jobs:
  include:
    - stage: unit
      script:
        - npm install
        - npm run compile
        - npm run test
    - stage: itest
      script:
        - npm install
        - npm run itest:build
        - npm run itest:run
    - stage: package
      script:
        - npm install
        - npm run compile
        - docker build -t tksukhu/nxplorerjs-microservice .
